-- 导入时必须使用 utf8mb4 客户端字符集，否则 COMMENT 中文会乱码
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

CREATE DATABASE IF NOT EXISTS xhblogs
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE xhblogs;

CREATE TABLE IF NOT EXISTS posts (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '文章自增主键',
  slug VARCHAR(191) NOT NULL UNIQUE COMMENT '文章唯一标识，用于路由',
  title VARCHAR(255) NOT NULL COMMENT '文章标题',
  description TEXT NULL COMMENT '文章摘要',
  cover TEXT NULL COMMENT '封面图 URL',
  tags_json JSON NULL COMMENT '文章标签 JSON 数组',
  body_markdown LONGTEXT NOT NULL COMMENT 'Markdown 正文',
  published_at DATETIME NULL COMMENT '发布时间',
  status VARCHAR(20) NOT NULL DEFAULT 'published' COMMENT '状态：draft/published',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_posts_published_at (published_at),
  INDEX idx_posts_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='博客文章主表';

CREATE TABLE IF NOT EXISTS chatters (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '杂谈自增主键',
  slug VARCHAR(191) NOT NULL UNIQUE COMMENT '杂谈唯一标识，用于路由',
  title VARCHAR(255) NOT NULL COMMENT '杂谈标题',
  mood VARCHAR(100) NULL COMMENT '心情字段',
  cover TEXT NULL COMMENT '封面图 URL',
  tags_json JSON NULL COMMENT '杂谈标签 JSON 数组',
  body_markdown LONGTEXT NOT NULL COMMENT 'Markdown 正文',
  published_at DATETIME NULL COMMENT '发布时间',
  status VARCHAR(20) NOT NULL DEFAULT 'published' COMMENT '状态：draft/published',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_chatters_published_at (published_at),
  INDEX idx_chatters_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='杂谈内容主表';

CREATE TABLE IF NOT EXISTS moments (
  id VARCHAR(191) PRIMARY KEY COMMENT '说说 ID（业务主键）',
  content LONGTEXT NOT NULL COMMENT '说说正文',
  location VARCHAR(255) NULL COMMENT '地理位置',
  images_json JSON NULL COMMENT '图片 URL JSON 数组',
  published_at DATETIME NULL COMMENT '发布时间',
  status VARCHAR(20) NOT NULL DEFAULT 'published' COMMENT '状态：draft/published',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_moments_published_at (published_at),
  INDEX idx_moments_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='说说动态表';

CREATE TABLE IF NOT EXISTS friends (
  id VARCHAR(191) PRIMARY KEY COMMENT '友链 ID',
  name VARCHAR(255) NOT NULL COMMENT '友链名称',
  url TEXT NOT NULL COMMENT '友链地址',
  description TEXT NULL COMMENT '友链描述',
  avatar TEXT NULL COMMENT '头像 URL',
  theme_color VARCHAR(64) NULL COMMENT '主题色',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序序号（越小越靠前）',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='友链数据表';

CREATE TABLE IF NOT EXISTS projects (
  id VARCHAR(191) PRIMARY KEY COMMENT '项目 ID',
  name VARCHAR(255) NOT NULL COMMENT '项目名',
  description TEXT NULL COMMENT '项目描述',
  icon VARCHAR(50) NULL COMMENT '项目图标（emoji 等）',
  github_url TEXT NULL COMMENT 'GitHub 地址',
  tags_json JSON NULL COMMENT '项目标签 JSON 数组',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序序号',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目展示表';

CREATE TABLE IF NOT EXISTS albums (
  id VARCHAR(191) PRIMARY KEY COMMENT '相册 ID',
  title VARCHAR(255) NOT NULL COMMENT '相册标题',
  description TEXT NULL COMMENT '相册描述',
  cover TEXT NULL COMMENT '相册封面 URL',
  date_label VARCHAR(50) NULL COMMENT '展示日期标签（如 2026.01）',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序序号',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='相册主表';

CREATE TABLE IF NOT EXISTS album_photos (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '照片自增主键',
  album_id VARCHAR(191) NOT NULL COMMENT '所属相册 ID',
  photo_url TEXT NOT NULL COMMENT '照片 URL',
  caption TEXT NULL COMMENT '照片描述',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序序号',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_album_photos_album_id (album_id),
  CONSTRAINT fk_album_photos_album FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='相册照片明细表';

CREATE TABLE IF NOT EXISTS site_settings (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '设置自增主键',
  setting_key VARCHAR(191) NOT NULL UNIQUE COMMENT '设置键名（唯一）',
  value_text LONGTEXT NULL COMMENT '设置值（文本或 JSON 字符串）',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='站点配置键值表';
